/** Iconify (lucide) classes for the PDF UI. Use as `<span class="{icons.zoomIn} size-4"></span>`. */
export const toolIcons: Record<string, string> = {
	select: 'icon-[lucide--mouse-pointer-2]',
	hand: 'icon-[lucide--hand]',
	highlight: 'icon-[lucide--highlighter]',
	underline: 'icon-[lucide--underline]',
	strikeout: 'icon-[lucide--strikethrough]',
	squiggly: 'icon-[lucide--spline]',
	area: 'icon-[lucide--square-dashed]',
	note: 'icon-[lucide--sticky-note]',
	ink: 'icon-[lucide--pen-line]',
	rect: 'icon-[lucide--square]',
	ellipse: 'icon-[lucide--circle]',
	line: 'icon-[lucide--slash]',
	arrow: 'icon-[lucide--move-up-right]',
	freetext: 'icon-[lucide--type]',
	eraser: 'icon-[lucide--eraser]'
};

export const icons = {
	zoomIn: 'icon-[lucide--zoom-in]',
	zoomOut: 'icon-[lucide--zoom-out]',
	prev: 'icon-[lucide--chevron-left]',
	next: 'icon-[lucide--chevron-right]',
	up: 'icon-[lucide--chevron-up]',
	down: 'icon-[lucide--chevron-down]',
	rotateCw: 'icon-[lucide--rotate-cw]',
	rotateCcw: 'icon-[lucide--rotate-ccw]',
	panel: 'icon-[lucide--panel-left]',
	search: 'icon-[lucide--search]',
	annotate: 'icon-[lucide--pen-tool]',
	download: 'icon-[lucide--download]',
	close: 'icon-[lucide--x]',
	undo: 'icon-[lucide--undo-2]',
	redo: 'icon-[lucide--redo-2]',
	sun: 'icon-[lucide--sun]',
	moon: 'icon-[lucide--moon]',
	palette: 'icon-[lucide--palette]',
	columns: 'icon-[lucide--columns-2]',
	notes: 'icon-[lucide--message-square-text]',
	list: 'icon-[lucide--list-tree]',
	external: 'icon-[lucide--external-link]',
	import: 'icon-[lucide--file-down]',
	back: 'icon-[lucide--arrow-left]',
	more: 'icon-[lucide--ellipsis]',
	eye: 'icon-[lucide--eye]',
	eyeOff: 'icon-[lucide--eye-off]',
	trash: 'icon-[lucide--trash-2]',
	copy: 'icon-[lucide--copy]',
	comment: 'icon-[lucide--message-square-plus]',
	map: 'icon-[lucide--map]',
	book: 'icon-[lucide--book-open]',
	layers: 'icon-[lucide--layers]',
	print: 'icon-[lucide--printer]',
	frame: 'icon-[lucide--square-dashed-bottom]'
};
